### ISSUE TITLE
Tracking issue for upstream issues

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize-dbt-utils#16]
I've identified at least three missing features in `materialized` that are blocking the remaining macros in this repo:

* [x] https://github.com/MaterializeInc/database-issues/issues/1065
* [x] https://github.com/MaterializeInc/database-issues/issues/3083
* [x] https://github.com/MaterializeInc/database-issues/issues/3084

I didn't do a great job of recording precisely _which_ macros were blocked by which feature, but as soon as one of those features land, we can try enabling _all_ the macros, and then re-disable those that are still failing.

**Comment by benesch** [comment]
These are all sufficiently well fixed upstream. I've updated MaterializeInc/materialize#15 accordingly.
